POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 2",
}

######

GET http://localhost:8080/category/797a635e-5836-4368-a7ae-72a831d00cc7 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

######

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

######

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 2",
    "description": "Product 2 description",
    "category_id": "797a635e-5836-4368-a7ae-72a831d00cc7",
    "image_url": "https://static.wikia.nocookie.net/onepiece/images/c/ca/Izo_Anime_Post_Timeskip_Infobox.png/revision/latest?cb=20210630180101&path-prefix=pt",
    "PRICE": 49.99
}

######

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

######

GET http://localhost:8080/product/category/797a635e-5836-4368-a7ae-72a831d00cc7 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

######

GET http://localhost:8080/product/3aa589fb-0c8f-4fac-a5d9-76c4fbb56afc HTTP/1.1
Host: localhost:8080
Content-Type: application/json